export const ActionTypes = {
    GET_NUMBER_CART: 'GET_NUMBER_CART',
    ADD_CART:'ADD_CART',
    DECREASE_QUANTITY: 'DECREASE_QUANTITY',
    DELETE_CART: 'DELETE_CART',
    EMPTY_CART: 'EMPTY_CART',
    GET_TOTAL_CART: 'GET_TOTAL_CART'
}
